openapi: 3.0.0
info:
  version: 1.0.0
  title: node home Work
  description: node home work api 설계

servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: mini2
    url: http://localhost:4000
paths:
  /api/users:
    post:
      summary: 회원가입
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                nick:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
              example: # Sample object
                nick: test5
                email: test5@test5.com
                password: test5
                confirmPassword: test5
      responses:
        '200':
          description: 성공
        '401':
          description: 실패
  /api/users/auth:
    post:
      summary: 로그인
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example: # Sample object
                email: test5@test5.com
                password: test5
      responses:
        '201':
          description: 성공
        '401':
          description: 실패

  /api/postings:
    post:
      # security:
      #   - bearerAuth: []
      summary: 게시물 생성
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                title:
                  type: string
                imageUrl:
                  type: string
                text:
                  type: string
              example: # Sample object
                title: 글 내용
                imageUrl: 이미지
                text: 글 내용
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
    get:
      summary: 게시글 전체 조회
      response:
        '200':
          description: 성공
        '400':
          description: 실패

  /api/users/{userId}:
    get:
      summary: 프로필 페이지
      parameters:
        - in: path
          name: userId
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '400':
          description: 실패

  /api/postings/{postingId}:
    delete:
      # security:
      #   - bearerAuth: []
      summary: 특정 게시물 삭제
      parameters:
        - in: path
          name: userId
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
    patch:
      # security:
      #   - bearerAuth: []
      summary: 특정 게시물 수정
      parameters:
        - in: path
          name: userId
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                imageUrl:
                  type: string
                title:
                  type: string
                text:
                  type: string
              example: # Sample object
                imageUrl: 이미지
                title: 글 내용
                text: 글 내용
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
    get:
      # security:
      #   - bearerAuth: []
      summary: 특정 게시물 조회
      parameters:
        - in: path
          name: postingId
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
  /api/postings/{postingId}/like:
    post:
      summary: 좋아요
      parameters:
        - in: path
          name: postingId
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
  /api/postings/{postingId}/comments:
    post:
      # security:
      #   - bearerAuth: []
      summary: 댓글 생성
      parameters:
        - in: path
          name: postingId
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                text:
                  type: string

              example: # Sample object
                text: 글 내용
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
    get:
      # security:
      #   - bearerAuth: []
      summary: 댓글 전체 조회
      parameters:
        - in: path
          name: postingId
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
    patch:
      # security:
      #   - bearerAuth: []
      summary: 댓글 수정
      parameters:
        - in: path
          name: postingId
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                text:
                  type: string
              example: # Sample object
                text: 글 내용
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
    delete:
      # security:
      #   - bearerAuth: []
      summary: 댓글 삭제
      parameters:
        - in: path
          name: postingId
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '400':
          description: 실패
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
